<a href="https://colab.research.google.com/github/OJO44/Python-Data-Analysis/blob/main/Numpy_Daily_Practice_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Daily Exercise 2

In [1]:
import numpy as np


In [7]:
#16. How to add a border (filled with 0's) around an existing array
arr1 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(arr1)
arr2 = np.zeros_like(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [8]:
#17. What is the result of the following expression
0 * np.nan

nan

In [9]:
np.nan == np.nan

False

In [10]:
np.inf > np.nan

False

In [11]:
np.nan - np.nan

nan

In [12]:
np.nan in set([np.nan])

True

In [13]:
0.3 == 3 * 0.1

False

In [14]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
arr5 = np.zeros((5, 5))
values =  np.array([1, 2, 3, 4])
np.fill_diagonal(arr5[1:], values) #arr5[1:] selects a sub-array of arr5 starting from the second row (index 1) to the end of the array
print(arr5)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [17]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern
arr8= np.zeros((8, 8), dtype=int)
print(arr8)
arr8[::2, ::2] = 1  ## Fill even rows and even columns with 1
arr8[1::2, 1::2] =1 # # Fill odd rows and odd columns with 1
print("\n", arr8)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

 [[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [20]:
#20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
shape = (6, 7, 8)
index_1d = 100
index_x_y_z = np.unravel_index(index_1d, shape) #The np.unravel_index() function in NumPy is used to convert the flattened index back to a multi-dimensional index (x, y, z) based on the given shape.
print("index (x,y,z) of the 100t element is:", index_x_y_z)

index (x,y,z) of the 100t element is: (1, 5, 4)


In [21]:
#21. Create a checkerboard 8x8 matrix using the tile function
checkerboard = np.array([[0, 1], [1, 0]])
checkboard8 = np.tile(checkerboard, (4, 4)) #Using np.tile(checkerboard, (4, 4)), we replicate the checkerboard array to create an 8x8 checkerboard matrix by tiling it 4 times in both dimensions.
print(checkboard8)



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [22]:
#22. Normalize a 5x5 random matrix
matrix5 =  np.random.rand(5, 5)
Normal_matrix5 =  (matrix5- np.mean(matrix5)) / np.std(matrix5)
print(matrix5)
print("\n", Normal_matrix5)


[[0.45701961 0.40545487 0.50252746 0.47765625 0.60680513]
 [0.77452268 0.08393474 0.20880286 0.59867117 0.28619207]
 [0.88963546 0.14167663 0.80400561 0.52749913 0.82360555]
 [0.31672077 0.44941171 0.31447594 0.09796703 0.02108182]
 [0.51618848 0.2646318  0.1708389  0.02196874 0.95790365]]

 [[ 0.10452312 -0.08625158  0.27288904  0.18087272  0.65868641]
 [ 1.27919307 -1.27578348 -0.8138074   0.62859308 -0.52748961]
 [ 1.70507719 -1.06215513  1.38827141  0.36527706  1.46078553]
 [-0.41454221  0.07637606 -0.42284742 -1.22386805 -1.50832119]
 [ 0.3234309  -0.60725638 -0.95426311 -1.50503986  1.95764982]]


In [ ]:
#23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)


In [25]:
#24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
a = np.random.rand(5, 3)
b = np.random.rand(3,2)
c=  np.dot(a,b)
print(c)

[[0.61217108 0.8445912 ]
 [1.38898055 1.14583865]
 [1.25890283 1.20578009]
 [0.56856678 0.82039996]
 [1.15055775 0.57094902]]


In [26]:
#25. Given a 1D array, negate all elements which are between 3 and 8, in place
arr9 = np.array([1, 4, 6, 9, 2, 7, 5, 3, 8])
arr9[(arr9> 3) & (arr9< 8)] *= -1
print(arr9)

[ 1 -4 -6  9  2 -7 -5  3  8]


In [27]:
#26. What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
#27. Consider an integer vector Z, which of these expressions are legal?
# Z**Z
# 2 << Z >> 2
# Z <- Z
# 1j*Z
# Z/1/1
# Z<Z>Z

In [28]:
#28. What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-28-7280c4eaa491>:2: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-28-7280c4eaa491>:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-28-7280c4eaa491>:4: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

In [ ]:
#29. How to round away from zero a float array ?

In [29]:
#30. How to find common values between two arrays?
arr10 = np.array([1, 2, 3, 4, 5])
arr11 = np.array([2, 4, 5, 6, 7])
common_values = np.intersect1d(arr10, arr11)
print(common_values)



[2 4 5]
