<a href="https://colab.research.google.com/github/OJO44/Python-Data-Analysis/blob/main/NumpyDailyPractice3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
#32. Is the following expressions true?
np.sqrt(-1) == np.emath.sqrt(-1)

In [ ]:
#33. How to get the dates of yesterday, today and tomorrow?
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2024-03-25
Today: 2024-03-26
Tomorrow: 2024-03-27


In [ ]:
#34. How to get all the dates corresponding to the month of July 2016
# Create a range of dates for the month of July 2016
dates_july_2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

# Print all the dates corresponding to July 2016
print(dates_july_2016)




['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
#35. How to compute ((A+B)*(-A/2)) in place (without copy)?


In [ ]:
#36. Extract the integer part of a random array of positive numbers using 4 different methods

In [ ]:
#37. Create a 5x5 matrix with row values ranging from 0 to 4
arr1 = np.zeros((5, 5))
row_values = np.arange(5)
arr1 += row_values
print(arr1)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [7]:
#38. Consider a generator function that generates 10 integers and use it to build an array
def generator():
  for i in range(10):
    yield i  # yield is used to return values one at a time, while return exits the function entirely

arr2 = np.array(list(generator()))
print(arr2)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
#39. Create a vector of size 10 with values ranging from 0 to 1, both excluded
arr3 = np.linspace(0,1,10, endpoint= False)
print(arr3)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [17]:
#40. Create a random vector of size 10 and sort it
arr4 = np.random.rand(10)
print(arr4)
arr4.sort()

[0.35867614 0.77203703 0.28774144 0.37697523 0.04410084 0.07610289
 0.96894006 0.43734112 0.44191617 0.74357282]


In [18]:
#41. How to sum a small array faster than np.sum
arr5 = np.array([1,2,3,4,5,6,7,8])
result = sum(arr5)
print(result)

36


In [19]:
#42. Consider two random array A and B, check if they are equal
A = np.array([1,2,3,4])
B = np.array ([5,6,7,8])
are_equal = np.array_equal(A,B)
print(are_equal)

False


In [21]:
#43. Make an array immutable (read-only)
arr6 = np.array([1,2,3,4,5,6])
arr6.setflag(write= False)

arr6[4] = 20
print(arr6)

SyntaxError: invalid syntax (<ipython-input-21-45ea4346f87e>, line 4)

In [ ]:
#44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates


In [22]:
#45. Create random vector of size 10 and replace the maximum value by 0
arr7 = np.random.random(10)
max_value = np.argmax(arr7)
arr7[max_value] =0
print(arr7)


[0.         0.68651755 0.83241927 0.53048251 0.21790792 0.55673658
 0.75776598 0.19225594 0.13939119 0.20107688]
