<a href="https://colab.research.google.com/github/OJO44/Python-Data-Analysis/blob/main/NumpyWeeklyProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#61 Find the nearest value from a given value in an array
import numpy as np

def get_nearest_value(arr, value):
    arr = np.array(arr)  # Convert input list to a NumPy array
    idx = np.abs(arr - value).argmin()  # Calculate the absolute difference between each element in the array and the specified value
    return arr[idx]  # Return the nearest value

my_array = [10, 20, 30, 40, 50]
target_value = 25
nearest_value = get_nearest_value(my_array, target_value)  # Call the function get_nearest_value
print(f"Nearest value to {target_value} in the array is: {nearest_value}")



Nearest value to 25 in the array is: 20


In [ ]:
#62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator
arr1 = np.array([[10, 20, 30]])
arr2 = np.array([[40], [50], [60]])

Iterator  = np.nditer([arr1, arr2])  # Create an iterator over both arrays
total_sum = 0
for x, y in Iterator:
    total_sum += x + y

print(f"Sum of arr1 and arr2: {total_sum}")


Sum of arr1 and arr2: 630


In [ ]:
#64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?


In [16]:
#65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
import numpy as np

# Vector X
X = np.array([10, 20, 30, 40, 50])

# Index list I
I = np.array([1, 3, 9, 3, 4])

# Create an array F and accumulate elements of X based on the index list I
F = np.bincount(I, weights=X)

print(F)


[ 0. 10.  0. 60. 50.  0.  0.  0.  0. 30.]


In [ ]:
#66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors


In [ ]:
#67. Considering a four dimensions array, how to get sum over the last two axis at once?

In [15]:
#68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices
import numpy as np
# Create the one-dimensional vector D
D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
# Create the vector S of subset indices
S = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2])
# Compute the means of subsets of D using S
means = np.bincount(S, weights=D) / np.bincount(S)
print(means)


[2. 5. 8.]


In [14]:
#69. How to get the diagonal of a dot product?
arr5 = np.array([[3, 4], [2, 2]])
arr6 = np.array([[2, 1], [5, 2]])
result = np.diagonal(np.dot(arr5, arr6)) # TO TRANSPOSE USE ARR.T
print(result)

[26  6]


In [13]:
#70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?



In [10]:
#71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
arr3= np.random.rand(5,5,3)
arr4= np.random.rand(5,5)
result = arr3 * arr4[:,:,None]
print(result)


[[[0.22866115 0.16341283 0.19361946]
  [0.14229835 0.07555214 0.19527446]
  [0.26805742 0.24440819 0.32264718]
  [0.0036574  0.01545094 0.0537127 ]
  [0.0346826  0.0070427  0.01992664]]

 [[0.40915945 0.15800437 0.16982437]
  [0.41294204 0.40034646 0.31385663]
  [0.03484862 0.29631522 0.21067294]
  [0.04733746 0.46298055 0.00419647]
  [0.25841131 0.07718987 0.29616033]]

 [[0.01998364 0.01728268 0.00433919]
  [0.17693724 0.78184684 0.56578376]
  [0.02794514 0.09538858 0.0152516 ]
  [0.07100128 0.71125691 0.02467199]
  [0.05987224 0.00310754 0.0945904 ]]

 [[0.42125805 0.34808947 0.11610137]
  [0.01067812 0.00511087 0.01023989]
  [0.19651775 0.20984383 0.58695579]
  [0.33258964 0.16322069 0.19304637]
  [0.1421696  0.50911042 0.50236595]]

 [[0.01105545 0.00970368 0.02553568]
  [0.04860953 0.35652813 0.41406536]
  [0.35059407 0.3166952  0.00111853]
  [0.12593226 0.32954307 0.59701315]
  [0.47990793 0.01345207 0.71781291]]]


In [6]:
#72. How to swap two rows of an array?
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)
arr[[0,1]]=arr[[1,0]]
print("\n", arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]

 [[40 50 60]
 [10 20 30]
 [70 80 90]]


In [ ]:
#73 Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)

In [ ]:
#74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
#75. How to compute averages using a sliding window over an array? (★★★)


In [ ]:
#76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
#77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
#78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
#79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
#80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)

In [ ]:
#81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [19]:
#82. Compute a matrix rank (★★★)
matrix1 = np.array([[1, 2], [4, 3], [8, 9]])

# Compute the rank of the matrix
rank = np.linalg.matrix_rank(matrix1)  #np.linalg.matrix_rank: This is a function provided by NumPy's linear algebra module (np.linalg). It calculates the rank of a matrix using its singular value decomposition (SVD).

print(rank)


2


In [18]:
#83. How to find the most frequent value in an array?
# Assuming arr is the input array
arr7 = np.array([1, 2, 3, 2, 2, 3,4])

# Find the most frequent value
most_frequent_value = np.bincount(arr7).argmax()

print(most_frequent_value)


2


In [ ]:
#84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)


In [ ]:
#85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
# 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [21]:
#87 Consider a 16x16 array, how to get the block-sum (block size is 4x4)
# Create a 16x16 array
arr8= np.random.randint(1, 10, (16, 16))
print(arr8)
# Reshape and sum to get the block-sum
block_sum = arr8.reshape(4, 4, 4, 4).sum(axis=(1, 3))

print("\n", block_sum)


[[1 6 3 2 4 7 6 2 1 3 9 9 1 6 6 7]
 [3 8 9 8 7 7 2 6 4 6 3 5 5 4 7 1]
 [8 1 6 7 7 1 4 4 3 7 7 2 1 1 4 8]
 [2 4 7 8 6 3 6 8 4 3 7 5 6 6 2 3]
 [4 9 5 7 8 3 6 1 6 7 1 3 4 5 6 2]
 [9 5 1 7 6 3 8 1 4 8 9 9 9 7 6 7]
 [3 3 7 1 1 9 6 8 5 9 7 8 5 6 1 8]
 [1 9 4 7 4 6 3 1 5 8 1 3 5 5 5 8]
 [8 9 2 7 1 2 9 9 1 4 5 8 9 1 1 6]
 [3 5 3 4 8 5 4 2 8 1 4 6 3 9 5 8]
 [2 9 5 5 1 9 4 6 7 4 8 9 4 3 6 4]
 [3 5 4 7 9 6 7 5 6 2 5 3 3 9 3 8]
 [5 8 4 9 7 6 7 4 3 2 6 2 4 3 3 8]
 [3 1 9 7 9 9 2 7 6 4 5 4 9 2 7 1]
 [6 6 2 9 8 6 1 8 4 5 8 8 5 4 6 5]
 [4 6 9 7 6 6 9 7 9 1 1 6 5 1 7 6]]

 [[ 83  80  78  68]
 [ 82  74  93  89]
 [ 81  87  81  82]
 [ 95 102  74  76]]


In [ ]:
#88. How to implement the Game of Life using numpy arrays? (★★★)

In [24]:
#89 How to get the n largest values of an array (★★★
arr10 = np.array([10, 5, 2, 12, 3, 9])
n = 3
# Get the n largest values of the array
largest_values = arr10[np.argpartition(-arr10, n)[:n]]
print(largest_values)


[12 10  9]


In [25]:
#90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item)
from itertools import product

# Assuming vec1, vec2, vec3 are the input vectors
vec1 = [0, 2]
vec2 = [4, 2]
vec3 = [7, 3]

# Build the cartesian product of the input vectors
cartesian_product = np.array(list(product(vec1, vec2, vec3)))

print(cartesian_product)


[[0 4 7]
 [0 4 3]
 [0 2 7]
 [0 2 3]
 [2 4 7]
 [2 4 3]
 [2 2 7]
 [2 2 3]]
