<a href="https://colab.research.google.com/github/OJO44/Python-Data-Analysis/blob/main/Numpydaily_practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**Numpy Exercise 1**

In [1]:
#1. Import numpy
import numpy as np


In [ ]:
#2. Print the numpy version and the configuration
print("numpy version:", np.__version__)
print("numpy configuration:")
print(np.show_config())

In [4]:
#3Create a null vector of size
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
#4. How to find the memory size of any array
null_vector = np.zeros(10)
memory_size = null_vector.nbytes
print(memory_size)

80


In [ ]:
#5. How to get the documentation of the numpy add function from the command line?




In [7]:
#6.  Create a null vector of size 10 but the fifth value which is 1
null_vector = np.zeros(10)
null_vector[4] = 1   # fifth value should be at index 4
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
#7. Create a vector with values ranging from 10 to 49
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
#8. Reverse a vector (first element becomes last)
reversed_vector = np.flip(vector)
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [18]:
#9. Create a 3x3 matrix with values ranging from 0 to 8
arr1 = np.arange(9).reshape(3, 3)
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0]) #converting the list to array
non_zero_indices = np.nonzero(arr)

print(non_zero_indices)

(array([0, 1, 4]),)


In [20]:
# 11. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
#12. Create a 3x3x3 array with random values
arr2 = np.random.rand(3, 3, 3)
print(arr2)

[[[0.48760805 0.06152975 0.74529774]
  [0.41099063 0.41671385 0.07169539]
  [0.01518738 0.90610224 0.96629117]]

 [[0.32562384 0.73593834 0.36465664]
  [0.1536566  0.1393652  0.5605763 ]
  [0.85763525 0.93869512 0.40834122]]

 [[0.44076349 0.53948276 0.83704105]
  [0.746907   0.26073091 0.51063307]
  [0.05658264 0.59552029 0.58327256]]]


In [24]:
#13. Create a 10x10 array with random values and find the minimum and maximum values
arr3 = np.random.rand(10, 10)
min_value = np.min(arr3)
max_value = np.max(arr3)
print(arr3)
print("minimum value = : ",  min_value)
print("maximum value = : ",  max_value)

[[0.53642951 0.07420838 0.30610478 0.96578151 0.34886282 0.16202149
  0.88182263 0.65060774 0.11256105 0.52371759]
 [0.87609973 0.06147563 0.09355151 0.77388206 0.63358136 0.19435766
  0.21804506 0.31436173 0.96507058 0.4699091 ]
 [0.84759489 0.6781414  0.44431816 0.88900648 0.01739308 0.44974117
  0.70365014 0.79634257 0.67722886 0.67898715]
 [0.25894264 0.87277949 0.89607026 0.01421448 0.65656327 0.34746905
  0.58229226 0.19769152 0.05476155 0.24636491]
 [0.84329402 0.18077419 0.53475857 0.97030182 0.7185597  0.89880946
  0.5002975  0.3693113  0.36368102 0.11702527]
 [0.73978662 0.43709705 0.16375249 0.14308518 0.1083215  0.28055879
  0.75674849 0.51505603 0.60056179 0.43705874]
 [0.29097814 0.67291113 0.15432774 0.72855499 0.28309098 0.97431847
  0.40428054 0.17763544 0.44399978 0.39368774]
 [0.01618372 0.86376381 0.0548817  0.70356354 0.12083343 0.68994769
  0.69389154 0.17901957 0.95926361 0.76463725]
 [0.05933999 0.31365718 0.84712469 0.05028225 0.59884053 0.89863508
  0.64106808

In [26]:
# 14. Create a random vector of size 30 and find the mean value
arr3 = np.random.rand(30)
mean_value = np.mean(arr3)
print(arr3)
print("\nmean value =: ", mean_value)

[0.02169592 0.60230697 0.55412606 0.85228251 0.64391274 0.87389544
 0.67095966 0.02391829 0.732996   0.0022221  0.03961614 0.79467685
 0.23095883 0.86271234 0.53501529 0.97037981 0.63636217 0.24421597
 0.72634152 0.83539474 0.5032645  0.35513631 0.3924731  0.92424986
 0.8686805  0.25122553 0.75422265 0.03978877 0.39038355 0.48716042]

mean value =:  0.5273524836673166


In [30]:
#15. Create a 2d array with 1 on the border and 0 inside
arr5 = np.zeros((3,3))
print(arr5)
arr5[0, :] = 1 #0 indicates the index of the first row
arr5[-1, :] = 1 # 1 indicates the index of the last row
arr5[:, 0] = 1   #0 indicates the index of the first column
arr5[:, -1] = 1  # -1 indicates the index of the last column
print(arr5)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
