<a href="https://colab.research.google.com/github/OJO44/Python-Data-Analysis/blob/main/NumpyDailyPractice3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
#32. Is the following expressions true?
np.sqrt(-1) == np.emath.sqrt(-1)

In [ ]:
#33. How to get the dates of yesterday, today and tomorrow?
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2024-03-25
Today: 2024-03-26
Tomorrow: 2024-03-27


In [ ]:
#34. How to get all the dates corresponding to the month of July 2016
# Create a range of dates for the month of July 2016
dates_july_2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

# Print all the dates corresponding to July 2016
print(dates_july_2016)




['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
#35. How to compute ((A+B)*(-A/2)) in place (without copy)?


In [ ]:
#36. Extract the integer part of a random array of positive numbers using 4 different methods

In [ ]:
#37. Create a 5x5 matrix with row values ranging from 0 to 4
arr1 = np.zeros((5, 5))
row_values = np.arange(5)
arr1 += row_values
print(arr1)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
